"""add community contact fields

Revision ID: 44c69e5d8a07
Revises: 001_add_users
Create Date: 2026-05-18 01:07:40.434725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44c69e5d8a07'
down_revision: Union[str, Sequence[str], None] = '001_add_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_requests', 'token_version')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'name')
    op.add_column('access_requests', sa.Column('token_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
