"""add extended fields to pitch model

Revision ID: 844316478b1e
Revises: e81a3f45b441
Create Date: 2026-05-16 09:41:31.230023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844316478b1e'
down_revision: Union[str, Sequence[str], None] = 'e81a3f45b441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('group_size', sa.String(length=50), nullable=True))
    op.add_column('pitches', sa.Column('price_range', sa.String(length=50), nullable=True))
    op.add_column('pitches', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('pitches', sa.Column('frequency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'frequency')
    op.drop_column('pitches', 'duration')
    op.drop_column('pitches', 'price_range')
    op.drop_column('pitches', 'group_size')
    # ### end Alembic commands ###
