"""add community contact fields

Revision ID: d63fd5a499c8
Revises: 844316478b1e
Create Date: 2026-05-16 16:34:42.104071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63fd5a499c8'
down_revision: Union[str, Sequence[str], None] = '844316478b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('contact_name', sa.String(length=100), nullable=True))
    op.add_column('communities', sa.Column('contact_email', sa.String(length=200), nullable=True))
    op.add_column('communities', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.alter_column('pitches', 'venue_needs',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'venue_needs',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('communities', 'contact_phone')
    op.drop_column('communities', 'contact_email')
    op.drop_column('communities', 'contact_name')
    # ### end Alembic commands ###
