"""add email to venue requests

Revision ID: e81a3f45b441
Revises: 4969c172a681
Create Date: 2026-05-14 21:59:02.893016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81a3f45b441'
down_revision: Union[str, Sequence[str], None] = '4969c172a681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. add as nullable first
    op.add_column(
        'venue_requests',
        sa.Column('email', sa.String(), nullable=True)
    )

    # 2. fill old rows
    op.execute("""
        UPDATE venue_requests
        SET email = 'unknown@example.com'
        WHERE email IS NULL
    """)

    # 3. make it NOT NULL
    op.alter_column(
        'venue_requests',
        'email',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue_requests', 'email')
    # ### end Alembic commands ###
